# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Trent Edwards
description: >
  Data Analyst specializing in mortgage and financial operations, using SQL and Tableau to identify risk, improve loan prioritization, and support real-world decision-making.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Analyst<br><span style="color:#f58506">SQL • Tableau • Financial Analytics</span>
location: "Tacoma, WA"
resume_url: /docs/Trent_Edwards_Data_Analyst_Resume.pdf
avatar_image: 

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/trentedwardswa" # Add your linkedln handle
github: "https://github.com/TrentEdwards2112"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

